### PR TITLE
Fix update load balancer, use correct SANs

### PR DESCRIPTION
**Pull request by emosbaugh**

### CODE REVIEW

**Comment by emosbaugh** [comment]
join phase certs

```
DNS:ethan-aka-3, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:10.96.0.1, IP Address:10.138.0.56, IP Address:10.138.0.87, IP Address:10.138.0.66, IP Address:34.105.57.19, IP Address:10.138.0.75, IP Address:10.138.0.87
```

init phase certs

```
DNS:ethan-aka-3, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:10.96.0.1, IP Address:10.138.0.56, IP Address:10.138.0.75, IP Address:10.138.0.87, IP Address:10.138.0.87
```

**Comment by areed** [comment]
which is the load balancer ip and which is the private ip?

**Comment by emosbaugh** [comment]
i was changing from lb1 to lb2. im going to run through this again on a fresh install

```
primary ethan-aka-1                                   us-west1-b     n1-standard-4               10.138.0.66    34.105.57.19    RUNNING
primary ethan-aka-2                                   us-west1-b     n1-standard-4               10.138.0.45    34.83.65.245    RUNNING
primary ethan-aka-3                                   us-west1-b     n1-standard-4               10.138.0.56    34.105.114.184  RUNNING
secondary ethan-aka-4                                   us-west1-b     n1-standard-4               10.138.0.57    35.247.39.44    RUNNING
secondary ethan-aka-5                                   us-west1-b     n1-standard-4               10.138.0.17    35.203.145.159  RUNNING
secondary ethan-aka-6                                   us-west1-b     n1-standard-4               10.138.0.16    34.83.11.97     RUNNING
lb1 ethan-aka-7                                   us-west1-b     n1-standard-4               10.138.0.75    34.82.207.117   RUNNING
lb2 ethan-aka-8                                   us-west1-b     n1-standard-4               10.138.0.87    34.83.112.251   RUNNING
```

**Comment by areed** [comment]
You'd need 10.138.0.75, 10.138.0.87, and 10.138.0.56 to have both load balancer addresses and the private IP so the init phase should be ok, right?

**Comment by emosbaugh** [comment]
i think we hit a problem when we change the service cidr. then for init phase we get `10.96.0.1` rather than custom service cidr. i will run through that scenario

**Comment by areed** [comment]
For the record, join is better because it gets the full list of sans from kubeadm-config, including the service IP of kubernetes and both old and new load balancer addresses.

**Pull request merged**
